### ISSUE TITLE
docs: Placeholder in the search input is not centered

### ISSUE THREAD

**Issue by JanPetr** [algolia/magento#13]
@pixelastic:

> I have the following display when doing a search: 
> ![image](https://cloud.githubusercontent.com/assets/283419/18166652/9ad58e98-704c-11e6-82fe-b1bb856a85d1.png)
> 
> I'm using Chromium Version 48.0.2564.82 Ubuntu 15.04 (64-bit)

Copy of https://github.com/algolia/algoliasearch-magento/issues/565

**Comment by LukyVj** [comment]
Onn it

**Comment by LukyVj** [comment]
So, it seems it's not bugging anymore.
