### ISSUE TITLE
Responsive issues

### ISSUE THREAD

**Issue by royduin** [algolia/magento#35]
See:

<img width="497" alt="schermafbeelding 2017-02-03 om 16 26 28" src="https://cloud.githubusercontent.com/assets/1703233/22596996/0bf505da-ea2e-11e6-8a1f-acc01ece2948.png">

**Comment by JanPetr** [comment]
@LukyVj can you have a look?

**Comment by LukyVj** [comment]
Sure, sorry, I didn't tried on responsive. On it

**Comment by JanPetr** [comment]
Released, thanks!
